import '../../models/user_model.dart';
import '../../models/worker_model.dart';
import '../../models/service_request_model.dart';
import '../../models/chat_message_model.dart';
import '../../models/notification_model.dart';
import '../../models/family_member_model.dart';
import '../../models/complaint_model.dart';

class MockDataService {
  MockDataService._();

  static final UserModel defaultCustomer = UserModel(
    id: 'user_001',
    phoneNumber: '+91 98765 43210',
    fullName: 'Anjali Menon',
    dateOfBirth: '14 May 1994',
    gender: 'Female',
    address: 'Flat 4B, Palm Grove Residency, Panampilly Nagar',
    pincode: '682036',
    district: 'Ernakulam',
    language: 'en',
    role: UserRole.customer,
    helpPoints: 240,
    isElderlyModeEnabled: false,
  );

  static final WorkerModel primaryWorker = WorkerModel(
    id: 'worker_001',
    fullName: 'Ravi Kumar',
    phoneNumber: '+91 94471 23456',
    rating: 4.9,
    totalReviews: 148,
    completedJobs: 210,
    primarySkill: 'Groceries & Essentials',
    skills: const ['Groceries', 'Medicines', 'Errands', 'Parcel Pickup'],
    distanceKm: 1.2,
    etaMinutes: 12,
    verificationStatus: WorkerVerificationStatus.verified,
    isOnline: true,
    todayEarnings: 850.0,
    weeklyEarnings: 4920.0,
    withdrawableBalance: 3200.0,
    vehicleType: 'Hero Splendor (KL-07-CF-4210)',
    address: 'Kaloor, Ernakulam, Kerala',
  );

  static final List<WorkerModel> sampleWorkers = [
    primaryWorker,
    const WorkerModel(
      id: 'worker_002',
      fullName: 'Sujith Varghese',
      phoneNumber: '+91 98462 87654',
      rating: 4.8,
      totalReviews: 96,
      completedJobs: 130,
      primarySkill: 'Plumbing & Repairs',
      skills: ['Plumbing', 'Carpentry', 'General Repairs'],
      distanceKm: 2.1,
      etaMinutes: 18,
      verificationStatus: WorkerVerificationStatus.verified,
      isOnline: true,
      todayEarnings: 620.0,
      weeklyEarnings: 3800.0,
      withdrawableBalance: 2400.0,
      vehicleType: 'Honda Activa (KL-07-BQ-1188)',
      address: 'Edappally, Kochi, Kerala',
    ),
    const WorkerModel(
      id: 'worker_003',
      fullName: 'Lakshmi Priya',
      phoneNumber: '+91 97450 11223',
      rating: 5.0,
      totalReviews: 82,
      completedJobs: 115,
      primarySkill: 'Elderly Care & Hospital Escort',
      skills: ['Elderly Assistance', 'Hospital Assistance', 'Digital Assistance'],
      distanceKm: 0.8,
      etaMinutes: 8,
      verificationStatus: WorkerVerificationStatus.verified,
      isOnline: true,
      todayEarnings: 940.0,
      weeklyEarnings: 5100.0,
      withdrawableBalance: 4100.0,
      vehicleType: 'TVS Jupiter (KL-07-DN-9944)',
      address: 'Kadavanthra, Kochi, Kerala',
    ),
  ];

  static final List<ServiceRequestModel> sampleRequests = [
    ServiceRequestModel(
      id: 'req_101',
      customerId: 'user_001',
      customerName: 'Anjali Menon',
      customerPhone: '+91 98765 43210',
      serviceCategory: 'Groceries',
      title: 'Weekly Fresh Groceries & Milk',
      description: 'Milma Milk blue packet (500ml x 2), Jaya Rice 5kg, Fresh coriander and curry leaves from nearby store.',
      items: const [
        RequestItem(name: 'Milma Milk Blue (500ml)', quantity: '2 packets', estimatedPrice: 56),
        RequestItem(name: 'Jaya Rice (5kg bag)', quantity: '1 bag', estimatedPrice: 240),
        RequestItem(name: 'Coconut Oil (1L bottle)', quantity: '1 bottle', estimatedPrice: 190),
        RequestItem(name: 'Curry leaves & coriander', quantity: '1 bunch each', estimatedPrice: 30),
      ],
      pickupAddress: 'Lulu Hypermarket / Local Supermarket, Edappally',
      deliveryAddress: 'Flat 4B, Palm Grove Residency, Panampilly Nagar',
      urgency: RequestUrgency.urgent,
      preferredTime: 'Today, within 45 mins',
      status: RequestStatus.delivering,
      estimatedCost: 566.0,
      finalCost: 566.0,
      assignedWorker: primaryWorker,
      createdAt: DateTime.now().subtract(const Duration(minutes: 35)),
    ),
    ServiceRequestModel(
      id: 'req_102',
      customerId: 'user_001',
      customerName: 'Anjali Menon',
      customerPhone: '+91 98765 43210',
      serviceCategory: 'Medicines',
      title: 'Blood Pressure & Diabetes Medicines for Amma',
      description: 'Prescription uploaded. Telma 40mg (1 strip), Glycomet GP 1 (1 strip) from Neethi Medical Store.',
      items: const [
        RequestItem(name: 'Telma 40mg', quantity: '1 strip (15 tabs)', estimatedPrice: 135),
        RequestItem(name: 'Glycomet GP 1', quantity: '1 strip (10 tabs)', estimatedPrice: 110),
      ],
      pickupAddress: 'Neethi Medical Store, Panampilly Nagar',
      deliveryAddress: 'Flat 4B, Palm Grove Residency, Panampilly Nagar',
      urgency: RequestUrgency.urgent,
      preferredTime: 'Today, by 4:00 PM',
      status: RequestStatus.completed,
      estimatedCost: 285.0,
      finalCost: 285.0,
      tipAmount: 30.0,
      assignedWorker: primaryWorker,
      createdAt: DateTime.now().subtract(const Duration(days: 2)),
      rating: 5.0,
      review: 'Ravi was very polite, got the exact medicine brands and checked the expiry dates before billing!',
      tags: const ['On Time', 'Helpful', 'Careful'],
    ),
    ServiceRequestModel(
      id: 'req_103',
      customerId: 'user_001',
      customerName: 'Anjali Menon',
      customerPhone: '+91 98765 43210',
      serviceCategory: 'Elderly Assistance',
      title: 'Hospital Escort for Father\'s Eye Checkup',
      description: 'Assist father to Giridhar Eye Institute for routine IOP checkup and bring him back safely.',
      pickupAddress: 'Giridhar Eye Institute, Kadavanthra',
      deliveryAddress: 'House #12, Rose Villa, Thevara',
      urgency: RequestUrgency.scheduled,
      preferredTime: 'Tomorrow, 9:30 AM',
      status: RequestStatus.workerAssigned,
      estimatedCost: 350.0,
      finalCost: 350.0,
      assignedWorker: const WorkerModel(
        id: 'worker_003',
        fullName: 'Lakshmi Priya',
        phoneNumber: '+91 97450 11223',
        rating: 5.0,
        totalReviews: 82,
        completedJobs: 115,
        primarySkill: 'Elderly Care & Hospital Escort',
      ),
      createdAt: DateTime.now().subtract(const Duration(hours: 3)),
      familyMemberName: 'K. Madhavan Menon (Father)',
    ),
  ];

  static final List<ChatMessageModel> sampleChatMessages = [
    ChatMessageModel(
      id: 'm1',
      senderId: 'system',
      senderName: 'Nanma Security',
      isFromCustomer: false,
      content: 'Never share OTP, passwords or sensitive payment information.',
      type: MessageType.systemNotice,
      timestamp: DateTime.now().subtract(const Duration(minutes: 25)),
    ),
    ChatMessageModel(
      id: 'm2',
      senderId: 'worker_001',
      senderName: 'Ravi Kumar',
      isFromCustomer: false,
      content: 'Namaskaram Anjali! I am at the store now. They have fresh Milma milk packets.',
      type: MessageType.text,
      timestamp: DateTime.now().subtract(const Duration(minutes: 20)),
    ),
    ChatMessageModel(
      id: 'm3',
      senderId: 'user_001',
      senderName: 'Anjali Menon',
      isFromCustomer: true,
      content: 'Hello Ravi! Please check if the Jaya rice bag is the new harvest.',
      type: MessageType.text,
      timestamp: DateTime.now().subtract(const Duration(minutes: 18)),
    ),
    ChatMessageModel(
      id: 'm4',
      senderId: 'worker_001',
      senderName: 'Ravi Kumar',
      isFromCustomer: false,
      content: 'Yes checked! Harvest date is this month. I have added it to the cart and billing now.',
      type: MessageType.text,
      timestamp: DateTime.now().subtract(const Duration(minutes: 12)),
    ),
    ChatMessageModel(
      id: 'm5',
      senderId: 'worker_001',
      senderName: 'Ravi Kumar',
      isFromCustomer: false,
      content: 'I have started from the store. Arriving at your location in approx 8-10 minutes.',
      type: MessageType.text,
      timestamp: DateTime.now().subtract(const Duration(minutes: 4)),
    ),
  ];

  static final List<NotificationModel> sampleNotifications = [
    NotificationModel(
      id: 'notif_1',
      title: 'Worker is on the way! 🛵',
      message: 'Ravi Kumar has picked up your groceries and is arriving in 8 minutes.',
      category: NotificationCategory.worker,
      timestamp: DateTime.now().subtract(const Duration(minutes: 4)),
      isRead: false,
      actionRoute: '/tracking/req_101',
    ),
    NotificationModel(
      id: 'notif_2',
      title: 'Help Points Credited ⭐',
      message: 'You earned +50 Nanma Help Points for your completed medicine request.',
      category: NotificationCategory.request,
      timestamp: DateTime.now().subtract(const Duration(days: 1)),
      isRead: true,
      actionRoute: '/profile/points',
    ),
    NotificationModel(
      id: 'notif_3',
      title: 'Family Assist Update 👨‍👩‍👧',
      message: 'Lakshmi Priya accepted your request for Father\'s hospital escort tomorrow.',
      category: NotificationCategory.family,
      timestamp: DateTime.now().subtract(const Duration(hours: 3)),
      isRead: false,
      actionRoute: '/family',
    ),
    NotificationModel(
      id: 'notif_4',
      title: 'Community Safety Reminder',
      message: 'Nanma workers are verified with background checks and ID verification.',
      category: NotificationCategory.safety,
      timestamp: DateTime.now().subtract(const Duration(days: 3)),
      isRead: true,
    ),
  ];

  static final List<FamilyMemberModel> sampleFamilyMembers = [
    const FamilyMemberModel(
      id: 'fam_1',
      name: 'K. Madhavan Menon',
      relationship: 'Father (Age 74)',
      phoneNumber: '+91 94470 12345',
      address: 'House #12, Rose Villa, Thevara, Kochi',
      isElderly: true,
      activeRequestsCount: 1,
    ),
    const FamilyMemberModel(
      id: 'fam_2',
      name: 'Saraswathi Menon',
      relationship: 'Mother (Age 69)',
      phoneNumber: '+91 94471 99887',
      address: 'House #12, Rose Villa, Thevara, Kochi',
      isElderly: true,
      activeRequestsCount: 0,
    ),
  ];

  static final List<ComplaintModel> sampleComplaints = [
    ComplaintModel(
      id: 'comp_1',
      customerName: 'Vinod Pillai',
      workerName: 'Suresh Babu',
      requestId: 'req_884',
      issue: 'Delay of 35 minutes in picking up courier parcel.',
      priority: ComplaintPriority.medium,
      status: ComplaintStatus.investigating,
      adminNotes: 'Worker experienced vehicle puncture, notified customer late. Contacted both parties.',
      createdAt: DateTime.now().subtract(const Duration(hours: 6)),
    ),
    ComplaintModel(
      id: 'comp_2',
      customerName: 'Maya Thomas',
      workerName: 'Unknown',
      requestId: 'req_890',
      issue: 'Incorrect bill amount entered at local provision store.',
      priority: ComplaintPriority.high,
      status: ComplaintStatus.resolved,
      adminNotes: 'Difference of ₹45 refunded directly to customer wallet. Warning issued.',
      createdAt: DateTime.now().subtract(const Duration(days: 1)),
    ),
  ];
}
