import 'package:flutter/material.dart';

class ServiceCategoryModel {
  final String id;
  final String title;
  final String titleMalayalam;
  final String description;
  final IconData iconData;
  final Color iconColor;
  final Color bgColor;
  final double basePrice;
  final String routePath;

  const ServiceCategoryModel({
    required this.id,
    required this.title,
    required this.titleMalayalam,
    required this.description,
    required this.iconData,
    required this.iconColor,
    required this.bgColor,
    required this.basePrice,
    required this.routePath,
  });

  static List<ServiceCategoryModel> get defaultCategories => const [
    ServiceCategoryModel(
      id: 'groceries',
      title: 'Groceries',
      titleMalayalam: 'പലചരക്ക് സാധനങ്ങൾ',
      description: 'Daily provisions, fresh vegetables & fruits delivered',
      iconData: Icons.shopping_basket_rounded,
      iconColor: Color(0xFF2E7D32),
      bgColor: Color(0xFFE8F5E9),
      basePrice: 50.0,
      routePath: '/services/grocery',
    ),
    ServiceCategoryModel(
      id: 'medicines',
      title: 'Medicines',
      titleMalayalam: 'മരുന്നുകൾ',
      description: 'Prescription purchase & prompt pharmacy delivery',
      iconData: Icons.medication_rounded,
      iconColor: Color(0xFF0D3B66),
      bgColor: Color(0xFFE3F2FD),
      basePrice: 40.0,
      routePath: '/services/medicine',
    ),
    ServiceCategoryModel(
      id: 'parcel',
      title: 'Parcel & Pickup',
      titleMalayalam: 'പാഴ്സൽ കൊറിയർ',
      description: 'Pick up or drop off small parcels, keys & documents',
      iconData: Icons.local_shipping_rounded,
      iconColor: Color(0xFFFFA726),
      bgColor: Color(0xFFFFF3E0),
      basePrice: 60.0,
      routePath: '/services/parcel',
    ),
    ServiceCategoryModel(
      id: 'elderly_care',
      title: 'Elderly Assistance',
      titleMalayalam: 'മുതിർന്നവർക്കുള്ള സഹായം',
      description: 'Companionship, check-ins, walking & reading support',
      iconData: Icons.volunteer_activism_rounded,
      iconColor: Color(0xFF1B5E20),
      bgColor: Color(0xFFE8F5E9),
      basePrice: 120.0,
      routePath: '/elderly',
    ),
    ServiceCategoryModel(
      id: 'hospital',
      title: 'Hospital Support',
      titleMalayalam: 'ആശുപത്രി സഹായം',
      description: 'OP ticket booking, wheel-chair assist & escorting',
      iconData: Icons.local_hospital_rounded,
      iconColor: Color(0xFF00897B),
      bgColor: Color(0xFFE0F2F1),
      basePrice: 150.0,
      routePath: '/services/home-service?cat=Hospital',
    ),
    ServiceCategoryModel(
      id: 'plumbing',
      title: 'Plumbing',
      titleMalayalam: 'പ്ലംബിംഗ്',
      description: 'Leak repairs, tap replacements and pipe fitting',
      iconData: Icons.plumbing_rounded,
      iconColor: Color(0xFF0288D1),
      bgColor: Color(0xFFE1F5FE),
      basePrice: 180.0,
      routePath: '/services/home-service?cat=Plumbing',
    ),
    ServiceCategoryModel(
      id: 'electrical',
      title: 'Electrical',
      titleMalayalam: 'ഇലക്ട്രിക്കൽ',
      description: 'Wiring, switches, fuse repairs and fan installations',
      iconData: Icons.electric_bolt_rounded,
      iconColor: Color(0xFFF57C00),
      bgColor: Color(0xFFFFF8E1),
      basePrice: 180.0,
      routePath: '/services/home-service?cat=Electrical',
    ),
    ServiceCategoryModel(
      id: 'carpentry',
      title: 'Carpentry',
      titleMalayalam: 'മരപ്പണി',
      description: 'Door locks, hinges, wood fixes and furniture repair',
      iconData: Icons.handyman_rounded,
      iconColor: Color(0xFF8D6E63),
      bgColor: Color(0xFFEFEBE9),
      basePrice: 200.0,
      routePath: '/services/home-service?cat=Carpentry',
    ),
    ServiceCategoryModel(
      id: 'appliance',
      title: 'Appliance Repair',
      titleMalayalam: 'ഉപകരണ റിപ്പയർ',
      description: 'Washing machines, fridges, mixies & gas stoves',
      iconData: Icons.home_repair_service_rounded,
      iconColor: Color(0xFF5E35B1),
      bgColor: Color(0xFFEDE7F6),
      basePrice: 220.0,
      routePath: '/services/home-service?cat=Appliance Repair',
    ),
    ServiceCategoryModel(
      id: 'cleaning',
      title: 'Cleaning',
      titleMalayalam: 'വൃത്തിയാക്കൽ',
      description: 'Home deep cleaning, kitchen sanitizing & yard tidying',
      iconData: Icons.cleaning_services_rounded,
      iconColor: Color(0xFF26A69A),
      bgColor: Color(0xFFE0F2F1),
      basePrice: 250.0,
      routePath: '/services/home-service?cat=Cleaning',
    ),
    ServiceCategoryModel(
      id: 'painting',
      title: 'Painting & Touch-up',
      titleMalayalam: 'പെയിന്റിംഗ്',
      description: 'Single room coats, wall patch-up and damp proofing',
      iconData: Icons.format_paint_rounded,
      iconColor: Color(0xFF43A047),
      bgColor: Color(0xFFE8F5E9),
      basePrice: 350.0,
      routePath: '/services/home-service?cat=Painting',
    ),
    ServiceCategoryModel(
      id: 'digital',
      title: 'Digital Assistance',
      titleMalayalam: 'ഡിജിറ്റൽ സഹായം',
      description: 'Phone setup, online bill payments & ticket bookings',
      iconData: Icons.devices_other_rounded,
      iconColor: Color(0xFF0D3B66),
      bgColor: Color(0xFFE3F2FD),
      basePrice: 80.0,
      routePath: '/services/home-service?cat=Digital Assistance',
    ),
    ServiceCategoryModel(
      id: 'document',
      title: 'Document Assistance',
      titleMalayalam: 'രേഖാ സഹായം',
      description: 'Akshaya errands, printing, xerox & certificate submission',
      iconData: Icons.description_rounded,
      iconColor: Color(0xFF6D4C41),
      bgColor: Color(0xFFFBE9E7),
      basePrice: 70.0,
      routePath: '/services/home-service?cat=Document Assistance',
    ),
    ServiceCategoryModel(
      id: 'other',
      title: 'Other Errands',
      titleMalayalam: 'മറ്റ് സേവനങ്ങൾ',
      description: 'Custom community requests, queue standing & errands',
      iconData: Icons.miscellaneous_services_rounded,
      iconColor: Color(0xFF66B86A),
      bgColor: Color(0xFFE8F5E9),
      basePrice: 60.0,
      routePath: '/requests/smart-request',
    ),
  ];
}
